name: Run global Trustify CI tests

on:
  workflow_call:
    inputs:
      tag:
        description: |
          The tag that should be used to pull all trustify related images.
          For example, if you wanted to set a nightly build for release-0.2, you would specify
          "release-0.2".
        required: false
        type: string
        default: latest
      operator_tag:
        description: |
          The tag name for operator to be used for setup, e.g. a build for release-0.3,
          you would specify "v0.3.0".
        required: false
        type: string
        default: latest
      component_name:
        description: |
          The name of the component being tested, ie server etc.
          Must correspond to an artifact storing the custom built image, named <component_name>,
          and should contain the file <component_name>.tar inside.
        required: false
        type: string
      run_api_tests:
        description: |
          A flag that determines whether the API tests should be run or not
        type: boolean
        required: false
        default: true
      run_ui_tests:
        description: |
          A flag that determines whether the UI tests should be run or not
        type: boolean
        required: false
        default: true
      api_tests_ref:
        description: |
          The branch or PR of the trustify-api-tests repository to clone.
          For a pull request, the reference format would be "refs/pull/${PR_NUMBER}/merge".
          For a branch, the reference format would just be the branch name.
          This input can be set automatically on a pull request by adding a string of the format:
            API tests PR: 140
          replacing "140" with the appropriate PR number. This will make it easier to coordinate changes
          that require updating the global tests as well.
        required: false
        type: string
        default: main
      ui_tests_ref:
        description: |
          The branch or PR of the trustify-ui-tests repository to clone.
          For a pull request, the reference format would be "refs/pull/${PR_NUMBER}/merge".
          For a branch, the reference format would just be the branch name.
          This input can be set automatically on a pull request by adding a string of the format:
            UI tests PR: 140
          replacing "140" with the appropriate PR number. This will make it easier to coordinate changes
          that require updating the global tests as well.
        required: false
        type: string
        default: main
  workflow_dispatch:
    inputs:
      tag:
        description: |
          The tag that should be used to pull all trustify related images.
          For example, if you wanted to set a nightly build for release-0.2, you would specify
          "release-0.2".
        required: false
        type: string
        default: latest
      operator_tag:
        description: |
          The tag name for operator to be used for setup, e.g. a build for release-0.3,
          you would specify "v0.3.0".
        required: false
        type: string
        default: latest
      component_name:
        description: |
          The name of the component being tested, ie server etc.
          Must correspond to an artifact storing the custom built image, named <component_name>,
          and should contain the file <component_name>.tar inside.
        required: false
        type: string
      run_api_tests:
        description: |
          A flag that determines whether the API tests should be run or not
        type: boolean
        required: false
        default: true
      run_ui_tests:
        description: |
          A flag that determines whether the UI tests should be run or not
        type: boolean
        required: true
        default: true
      api_tests_ref:
        description: |
          The branch or PR of the trustify-api-tests repository to clone.
          For a pull request, the reference format would be "refs/pull/${PR_NUMBER}/merge".
          For a branch, the reference format would just be the branch name.
          This input can be set automatically on a pull request by adding a string of the format:
            Go tests PR: 140
          replacing "140" with the appropriate PR number. This will make it easier to coordinate changes
          that require updating the global tests as well.
        required: false
        type: string
        default: main
      ui_tests_ref:
        description: |
          The branch or PR of the trustify-ui-tests repository to clone.
          For a pull request, the reference format would be "refs/pull/${PR_NUMBER}/merge".
          For a branch, the reference format would just be the branch name.
          This input can be set automatically on a pull request by adding a string of the format:
            UI tests PR: 140
          replacing "140" with the appropriate PR number. This will make it easier to coordinate changes
          that require updating the global tests as well.
        required: false
        type: string
        default: main

jobs:
  e2e-api-integration-tests:
    runs-on: ubuntu-latest
    if: ${{ inputs.run_api_tests }}
    steps:
      - name: Extract pull request number from inputs or PR description
        env:
          body: ${{ github.event.pull_request.body }}
        run: |
          PULL_REQUEST_NUMBER=$(echo ${body} | grep -oP '[A|a][P|p][I|i] [T|t]ests [P|p][R|r]: \K\d+' || true)
          [ -z "$PULL_REQUEST_NUMBER" ] \
            && API_TESTS_REF=${{ inputs.api_tests_ref }} \
            || API_TESTS_REF=refs/pull/$PULL_REQUEST_NUMBER/merge

          echo "API_TESTS_REF=${API_TESTS_REF}" >>"$GITHUB_ENV"
          echo "Using API_TESTS_REF \`${API_TESTS_REF}\`" >>"$GITHUB_STEP_SUMMARY"

      - name: Checkout api tests repo
        uses: actions/checkout@v4
        with:
          repository: carlosthe19916/trustify-api-tests
          path: trustify-api-tests
          ref: "${{ env.API_TESTS_REF }}"

      # TODO Should DRY this
      - name: set up docker buildx
        if: "${{ inputs.component_name != '' }}"
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        if: "${{ inputs.component_name != '' }}"
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.component_name }}
          path: /tmp

      - name: start minikube
        uses: carlosthe19916/trustify-operator/.github/actions/start-minikube@main
        if: "${{ startsWith(inputs.operator_tag, 'latest') }}"
        with:
          memory: "max"
          cpus: "max"

      # TODO: Could just load all images found in this artifact so that people can rebuild multiple components if needed
      - name: Load image
        if: "${{ inputs.component_name != '' }}"
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker load --input /tmp/${{ inputs.component_name }}.tar

      - name: install trustify
        uses: carlosthe19916/trustify-operator/.github/actions/install-trustify@main
        if: "${{ inputs.operator_tag == 'latest'}}"
        with:
          operator-bundle-image: "ghcr.io/trustification/trustify-operator-bundle:${{ inputs.operator_tag }}"
          server-image: "ghcr.io/trustification/trustd:${{ inputs.tag }}"
      # end DRY

      - name: Wait for Ingress and expose Trustify URL
        run: |
          external_ip=""
          echo $external_ip;
          while [[ -z $external_ip ]]
            do
              echo "Waiting for end point..."
                external_ip=$(kubectl get ingress myapp-trustify-server-ingress --template="{{range.status.loadBalancer.ingress}}{{.ip}}{{end}}" -n trustify);[[ -z $external_ip ]] &&
                echo $external_ip;
                sleep 10;
            done
          echo "End point ready:" &&
          echo $external_ip;
          echo "TRUSTIFY_URL=https://$(minikube ip)" >>$GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run tests
        run: mvn verify
        working-directory: trustify-api-tests
        env:
          TRUSTIFY_URL: "${{ env.TRUSTIFY_URL }}"

  e2e-ui-integration-tests:
    if: ${{ inputs.run_ui_tests }}
    runs-on: ubuntu-latest

    steps:
      - name: Extract pull request number from inputs or PR description
        env:
          body: ${{ github.event.pull_request.body }}
        run: |
          PULL_REQUEST_NUMBER=$(echo ${body} | grep -oP '[U|u][I|i] [T|t]ests [P|p][R|r]: \K\d+' || true)
          [ -z "$PULL_REQUEST_NUMBER" ] \
            && UI_TESTS_REF=${{ inputs.ui_tests_ref }} \
            || UI_TESTS_REF=refs/pull/$PULL_REQUEST_NUMBER/merge

          echo "UI_TESTS_REF=${UI_TESTS_REF}" >>"$GITHUB_ENV"
          echo "Using UI_TESTS_REF \`${UI_TESTS_REF}\`" >>"$GITHUB_STEP_SUMMARY"

      - name: Checkout ui tests repo
        uses: actions/checkout@v4
        with:
          repository: carlosthe19916/trustify-ui-tests
          path: trustify-ui-tests
          ref: "${{ env.UI_TESTS_REF }}"

      # TODO Should DRY this
      - name: set up docker buildx
        if: "${{ inputs.component_name != '' }}"
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        if: "${{ inputs.component_name != '' }}"
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.component_name }}
          path: /tmp

      - name: start minikube
        uses: carlosthe19916/trustify-operator/.github/actions/start-minikube@main
        with:
          memory: "max"
          cpus: "max"

      # TODO: Could just load all images found in this artifact so that people can rebuild multiple components if needed
      - name: Load image
        if: "${{ inputs.component_name != '' }}"
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker load --input /tmp/${{ inputs.component_name }}.tar

      - name: install trustify
        uses: carlosthe19916/trustify-operator/.github/actions/install-trustify@main
        if: "${{ inputs.operator_tag == 'latest'}}"
        with:
          operator-bundle-image: "ghcr.io/trustification/trustify-operator-bundle:${{ inputs.operator_tag }}"
          server-image: "ghcr.io/trustification/trustd:${{ inputs.tag }}"
          image-pull-policy: IfNotPresent
      # end DRY

      - name: Wait for Ingress and expose Trustify service
        run: |
          external_ip=""
          echo $external_ip;
          while [[ -z $external_ip ]]
            do
              echo "Waiting for end point..."
                external_ip=$(kubectl get ingress myapp-trustify-server-ingress --template="{{range.status.loadBalancer.ingress}}{{.ip}}{{end}}" -n trustify);[[ -z $external_ip ]] &&
                echo $external_ip;
                sleep 10;
            done
          echo "End point ready:" &&
          echo $external_ip;
          echo "TRUSTIFY_URL=https://$(minikube ip)" >>$GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: trustify-ui-tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: trustify-ui-tests
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: trustify-ui-tests
        env:
          PLAYWRIGHT_trustifyUrl: "${{ env.TRUSTIFY_URL }}"
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: trustify-ui-test-reports
          path: trustify-ui-tests/playwright-report/
