name: Trustify CI via Operator Bundle

on:
  workflow_call:
    inputs:
      artifact:
        description: |
          The name of the artifact storing custom images to be used during the CI run. All
          images stored in the artifact will be automatically loaded.
        type: string
        required: false
      operator_bundle:
        description: image uri for operator-bundle (ie. ghcr.io/<namespace>/<image-name>:<tag>). Must be pullable.
        type: string
        required: false
        default: ""
      server:
        description: image uri for the server (ie. ghcr.io/<namespace>/<image-name>:<tag>)
        type: string
        required: false
        default: ""
      server_postgres:
        description: image uri for server-postgres (ie. ghcr.io/<namespace>/<image-name>:<tag>)
        type: string
        required: false
        default: ""
      namespace:
        description: |
          Namespace for the trustify install.
        type: string
        required: false
        default: ""
      trustify_cr:
        description: |
          Full JSON encoded string representing the Trustify resource to be created.
        type: string
        required: false
        default: '{"kind":"Trustify","apiVersion":"org.trustify/v1alpha1","metadata":{"name":"myapp"},"spec":{}}'
      run_api_tests:
        description: |
          A flag that determines whether the API tests should be run or not
        type: boolean
        required: false
        default: true
      run_ui_tests:
        description: |
          A flag that determines whether the UI tests should be run or not
        type: boolean
        required: false
        default: true
      api_tests_ref:
        description: |
          The branch or PR of the trustify-ap-tests repository to clone.
          For a pull request, the reference format would be "refs/pull/${PR_NUMBER}/merge".
          For a branch, the reference format would just be the branch name.
          This input can be set automatically on a pull request by adding a string of the format:
            API tests PR: 140
          replacing "140" with the appropriate PR number. This will make it easier to coordinate changes
          that require updating the global tests as well.
        required: false
        type: string
        default: main
      ui_tests_ref:
        description: |
          The branch or PR of the trustify-ui-tests repository to clone.
          For a pull request, the reference format would be "refs/pull/${PR_NUMBER}/merge".
          For a branch, the reference format would just be the branch name.
          This input can be set automatically on a pull request by adding a string of the format:
            UI tests PR: 140
          replacing "140" with the appropriate PR number. This will make it easier to coordinate changes
          that require updating the global tests as well.
        required: false
        type: string
        default: main
      server_tests_ref:
        description: |
          The branch or PR of the Hub API tests from trustify repository to clone.
          For a pull request, the reference format would be "refs/pull/${PR_NUMBER}/merge".
          For a branch, the reference format would just be the branch name.
        required: false
        type: string
        default: main
  workflow_dispatch:
    inputs:
      operator_bundle:
        description: image uri for operator-bundle (ie. ghcr.io/<namespace>/<image-name>:<tag>). Must be pullable.
        type: string
        required: false
        default: "ghcr.io/carlosthe19916/trustify-operator-bundle:latest"
      namespace:
        description: |
          Namespace for the trustify install.
        type: string
        required: false
        default: ""
      trustify_cr:
        description: |
          Full JSON encoded string representing the Trustify resource to be created.
        type: string
        required: false
        default: '{"kind":"Trustify","apiVersion":"org.trustify/v1alpha1","metadata":{"name":"myapp"},"spec":{}}'
      run_api_tests:
        description: |
          A flag that determines whether the API tests should be run or not
        type: boolean
        required: false
        default: true
      run_ui_tests:
        description: |
          A flag that determines whether the UI tests should be run or not
        type: boolean
        required: false
        default: true
      api_tests_ref:
        description: |
          The branch or PR of the trustify-api-tests repository to clone.
          For a pull request, the reference format would be "refs/pull/${PR_NUMBER}/merge".
          For a branch, the reference format would just be the branch name.
          This input can be set automatically on a pull request by adding a string of the format:
            API tests PR: 140
          replacing "140" with the appropriate PR number. This will make it easier to coordinate changes
          that require updating the global tests as well.
        required: false
        type: string
        default: main
      ui_tests_ref:
        description: |
          The branch or PR of the trustify-ui-tests repository to clone.
          For a pull request, the reference format would be "refs/pull/${PR_NUMBER}/merge".
          For a branch, the reference format would just be the branch name.
          This input can be set automatically on a pull request by adding a string of the format:
            UI tests PR: 140
          replacing "140" with the appropriate PR number. This will make it easier to coordinate changes
          that require updating the global tests as well.
        required: false
        type: string
        default: main

env:
  operator_bundle: ttl.sh/trustify-operator-bundle-${{ github.sha }}:2h

jobs:
  check-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check operator image exists
        if: ${{ inputs.operator_bundle != '' }}
        env:
          SERVER: ${{ inputs.server }}
          POSTGRES: ${{ inputs.server_postgres }}
        run: |
          docker manifest inspect ${{ inputs.operator_bundle }}
          # My cheap way to check if any other image is set
          if [ -n "${SERVER}${POSTGRES}" ]; then
            echo "::warning:: operator_bundle takes precendent over any other image specified!"
            echo "::warning:: consider removing the image and setting it on the Trustify CR."
          fi
      - name: Check server image exists
        if: ${{ inputs.server != '' }}
        run: docker manifest inspect ${{ inputs.server }}
      - name: Check server_postgres image exists
        if: ${{ inputs.server_postgres != '' }}
        run: docker manifest inspect ${{ inputs.server_postgres }}

  e2e-api-integration-tests:
    needs: check-images
    if: ${{ inputs.run_api_tests }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract pull request number from inputs or PR description
        env:
          body: ${{ github.event.pull_request.body }}
        run: |
          PULL_REQUEST_NUMBER=$(echo ${body} | grep -oP '[U|u][I|i] [T|t]ests [P|p][R|r]: \K\d+' || true)
          [ -z "$PULL_REQUEST_NUMBER" ] \
            && UI_TESTS_REF=${{ inputs.ui_tests_ref }} \
            || UI_TESTS_REF=refs/pull/$PULL_REQUEST_NUMBER/merge

          echo "UI_TESTS_REF=${UI_TESTS_REF}" >>"$GITHUB_ENV"
          echo "Using UI_TESTS_REF \`${UI_TESTS_REF}\`" >>"$GITHUB_STEP_SUMMARY"

      - name: Checkout ui tests repo
        uses: actions/checkout@v4
        with:
          repository: carlosthe19916/trustify-ui-tests
          path: trustify-ui-tests
          ref: "${{ env.UI_TESTS_REF }}"

      # TODO Should DRY this
      - name: set up docker buildx
        if: ${{ inputs.artifact != '' }}
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        if: ${{ inputs.artifact != '' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: /tmp/images

      - name: Start minikube
        uses: carlosthe19916/trustify-operator/.github/actions/start-minikube@main
        with:
          memory: "max"
          cpus: "max"

      - name: Load images
        if: ${{ inputs.artifact != '' }}
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          for image in $(ls /tmp/images/*.tar); do
            docker load --input ${image}
          ; done

      - name: Make bundle
        if: ${{ inputs.operator_bundle == '' }}
        uses: carlosthe19916/trustify-operator/.github/actions/make-bundle@main
        with:
          operator_bundle: ${{ env.operator_bundle }}
          server: ${{ inputs.server }}
          server_postgres: ${{ inputs.server_postgres }}

      - name: Push bundle
        if: ${{ inputs.operator_bundle == '' }}
        run: docker push ${operator_bundle}

      - name: Install trustify
        uses: carlosthe19916/trustify-operator/.github/actions/install-trustify-bundle@main
        with:
          bundle_image: ${{ inputs.operator_bundle == '' && env.operator_bundle || inputs.operator_bundle }}
          namespace: ${{ inputs.namespace }}
          trustify_cr: ${{ inputs.trustify_cr }}
      # end DRY

      - name: Wait for Ingress and expose UI service
        run: |
          external_ip=""
          echo $external_ip;
          while [[ -z $external_ip ]]
            do
              echo "Waiting for end point..."
                external_ip=$(kubectl get ingress myapp-trustify-server-ingress --template="{{range.status.loadBalancer.ingress}}{{.ip}}{{end}}" -n trustify);[[ -z $external_ip ]] &&
                echo $external_ip;
                sleep 10;
            done
          echo "End point ready:" &&
          echo $external_ip;
          echo "UI_URL=https://$(minikube ip)" >>$GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: npm
      - name: Install dependencies
        run: npm ci
        working-directory: trustify-ui-tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: trustify-ui-tests
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: trustify-ui-tests
        env:
          PLAYWRIGHT_trustifyUrl: "${{ env.UI_URL }}"
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: trustify-ui-tests-report
          path: trustify-ui-tests/playwright-report/

  e2e-ui-integration-tests:
    needs: check-images
    # if: ${{ inputs.run_ui_tests }}
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: Extract pull request number from inputs or PR description
        env:
          body: ${{ github.event.pull_request.body }}
        run: |
          PULL_REQUEST_NUMBER=$(echo ${body} | grep -oP '[U|u][I|i] [T|t]ests [P|p][R|r]: \K\d+' || true)
          [ -z "$PULL_REQUEST_NUMBER" ] \
            && UI_TESTS_REF=${{ inputs.ui_tests_ref }} \
            || UI_TESTS_REF=refs/pull/$PULL_REQUEST_NUMBER/merge

          echo "UI_TESTS_REF=${UI_TESTS_REF}" >>"$GITHUB_ENV"
          echo "Using UI_TESTS_REF \`${UI_TESTS_REF}\`" >>"$GITHUB_STEP_SUMMARY"

      - name: Checkout ui tests repo
        uses: actions/checkout@v4
        with:
          repository: carlosthe19916/trustify-ui-tests
          path: trustify-ui-tests
          ref: "${{ env.UI_TESTS_REF }}"

      # TODO Should DRY this
      - name: set up docker buildx
        if: ${{ inputs.artifact != '' }}
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        if: ${{ inputs.artifact != '' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: /tmp/images

      - name: Start minikube
        uses: carlosthe19916/trustify-operator/.github/actions/start-minikube@main
        with:
          memory: "max"
          cpus: "max"

      - name: Load images
        if: ${{ inputs.artifact != '' }}
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          for image in $(ls /tmp/images/*.tar); do
            docker load --input ${image}
          ; done

      - name: Make bundle
        if: ${{ inputs.operator_bundle == '' }}
        uses: carlosthe19916/trustify-operator/.github/actions/make-bundle@main
        with:
          operator_bundle: ${{ env.operator_bundle }}
          server: ${{ inputs.server }}
          server_postgres: ${{ inputs.server_postgres }}

      - name: Push bundle
        if: ${{ inputs.operator_bundle == '' }}
        run: docker push ${operator_bundle}

      - name: Install trustify
        uses: carlosthe19916/trustify-operator/.github/actions/install-trustify-bundle@main
        with:
          bundle_image: ${{ inputs.operator_bundle == '' && env.operator_bundle || inputs.operator_bundle }}
          namespace: ${{ inputs.namespace }}
          trustify_cr: ${{ inputs.trustify_cr }}
      # end DRY

      - name: Wait for Ingress and expose UI service
        run: |
          external_ip=""
          echo $external_ip;
          while [[ -z $external_ip ]]
            do
              echo "Waiting for end point..."
                external_ip=$(kubectl get ingress myapp-trustify-server-ingress --template="{{range.status.loadBalancer.ingress}}{{.ip}}{{end}}" -n trustify);[[ -z $external_ip ]] &&
                echo $external_ip;
                sleep 10;
            done
          echo "End point ready:" &&
          echo $external_ip;
          echo "UI_URL=https://$(minikube ip)" >>$GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: npm
      - name: Install dependencies
        run: npm ci
        working-directory: trustify-ui-tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: trustify-ui-tests
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: trustify-ui-tests
        env:
          PLAYWRIGHT_trustifyUrl: "${{ env.UI_URL }}"
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: trustify-ui-tests-report
          path: trustify-ui-tests/playwright-report/
