name: Run Trustify nightly main branch tests

on:
  schedule:
    - cron: "5 3 * * *"
  workflow_dispatch:

jobs:
  main-nightly:
    uses: ./.github/workflows/global-ci.yml
    with:
      operator_bundle: "ghcr.io/trustification/trustify-operator-bundle:latest"
      tests_ref: main
      run_api_tests: true
      run_ui_tests: true
